spring:
  application:
    name: hhplus
  profiles:
    active: local
  datasource:
    name: HangHaePlusDataSource
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  data:
    redis:
      redisson:
        config: |
          singleServerConfig:
            address: "redis://localhost:6379"
            connectionPoolSize: 10
            connectionMinimumIdleSize: 5
            connectTimeout: 3000
            timeout: 3000
            retryAttempts: 3
            retryInterval: 1500
---
spring.config.activate.on-profile: local, test

spring:
  datasource:
    url: jdbc:mysql://localhost:3308/hhplus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver

app:
  crypto:
    secret-key:
      my-secret-key-16: test1234